CREATE OR REPLACE STORAGE INTEGRATION azure_retail_integration
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = AZURE
ENABLED = TRUE
AZURE_TENANT_ID = '{{AZURE_TENANT_ID}}'
STORAGE_ALLOWED_LOCATIONS = ('{{AZURE_STORAGE_URL}}');

DESC STORAGE INTEGRATION azure_retail_integration;

USE retail_db.bronze;

CREATE OR REPLACE STAGE adls_stage
STORAGE_INTEGRATION = azure_retail_integration
URL = '{{AZURE_STORAGE_URL}}';

ls @adls_stage;
